sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - rpm
before_install:
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
  ~/.m2/settings.xml
- git clone --depth=50 --branch=2.0 https://github.com/Graylog2/graylog2-server.git  /home/travis/build/alcampos/graylog2-server
- cd /home/travis/build/alcampos/graylog2-server; git checkout tags/2.3.0-alpha.3;
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true; cd /home/travis/build/alcampos/graylog-plugin-function-csv
- echo "finished before_install"
- pwd
- ls
before_deploy:
- mvn jdeb:jdeb && export RELEASE_DEB_FILE=$(ls target/*.deb)
- mvn rpm:rpm && export RELEASE_RPM_FILE=$(find target/ -name '*.rpm' | tail -1)
- rm -f target/original-*.jar
- export RELEASE_PKG_FILE=$(ls target/*.jar)
- echo "Deploying release to GitHub releases with the following files:"
- echo "$RELEASE_PKG_FILE"
- echo "$RELEASE_DEB_FILE"
- echo "$RELEASE_RPM_FILE"
deploy:
  provider: releases
  api_key:
    secure: V4svTNmplfNVKdO3T69SAzU/h1WEJvZ/T2nC2o0R3tfXjILLhIc5JYCyx6en/aEPhPOuaDPMETcjrhalaXodJKKl3JfIwIh+ucmDYePTf+oFxAI+xGgVzubK8U2f3ghwCXGG7MZ2FsFAEG4vlkY4NIQDnuC3T12Ho85IQsWIHJwpNowo631w93zVa2GWS5cggAOB3A6VnO6IGKFeh2fzrIYEHbN2/Hd/1psDL3RRV1UAMUqGoOerxqp7eyisnLdNndHoHevy4ggqQ4rt1kJsYKSPa/Ni7Nkk0awz8CHJuT+6qJVqkaqTAQR8r8rXTuMFefiai/xehdCv0WgQ1S1D55nJpI9Q1wDxivEE+o1qKgqtLvAc6ZBeX7S7lA/wicn0FoBosNq6dKrELJ6Erq/Mo+yEpXhm+9aIU4MhUOiWLpz88hA6YniPh46eiKiyvGvPhoJp8ANCs7YaaJEdRCpyGAaCWjG5yWkNTjQPGzjuH2yIfsoswGIWgq5dVebx1DRF1XVsoBAJy2Poqf4j6fjo/f0o2UqWFGfOO560cP7r1OP/KnvIkIZQ0uox3MvP5e27eCr4GHH5lmfQrHwudDXWatC2xgHiHrtRA2ZjMi591MlQUiqCdMZIjWi1+1kdC4BNqEBjF9exYVdNZv23vAVJsMWTO8k0iC3V/iOPMjiRkxg=
  file:
    - "${RELEASE_PKG_FILE}"
    - "${RELEASE_DEB_FILE}"
    - "${RELEASE_RPM_FILE}"
  deploy.skip_cleanup: true
  on:
    repo: alcampos/graylog-plugin-function-csv
    tags: true
